part of '../app_intl.dart';

const Map<String, String> _sourceEn = <String, String>{
  'home': 'Home',
  'calendar': 'Calendar',
  'favorites': 'Favorites',
  'translation': 'translation',
  'evaluate': 'Rate app',
  'share': 'Share {lapp}',
  'shareMsg': 'Hey! here is a very interesting evangelistic sharing'
      ' application \uD83D\uDC49 {url}',
  'appName': 'Biblical calendar',
  'lapp': 'the application',
  'verse': 'Verse',
  'noTranslation': 'No translation',
  'downloadLeastOneTranslate':
      'Please download at least one translation to access '
          'the application features',
  'ok': 'Okay',
  'confirmDelete': 'Confirmation of deletion',
  'reallyWantIt': 'Are you sure you want to delete the translation',
  'delete': 'Delete',
  'cancel': 'Cancel',
  'youHaveXTranslation': 'You have {count} translation{addS}',
  'addTranslation': 'Add translation',
  'def': 'Default',
  'markAsPrincipal': 'set as main translation',
  'favoriteNotFound': 'favorites not found',
  'textOfD': 'Text of the Day',
  'monday': 'Monday',
  'tuesday': 'Tuesday',
  'wednesday': 'Wednesday',
  'thursday': 'Thursday',
  'friday': 'Friday',
  'saturday': 'Saturday',
  'sunday': 'Sunday',
  'notFoundInCurrentTranslation':
      'not found in the current translation. Please',
  'select': 'Select',
  'or': 'Or',
  'download': 'Download',
  'appropriateTranslation': 'The appropriate translation',
  'language': 'Language',
  'size': 'Size',
  'downloaded': 'Downloaded',
  'downloading': 'Downloading',
  'updating': 'Update in progress',
  'updatingDb': 'Database update in progress',
  'error': 'Error',
  'errorDownloadDataMsg':
      'Error while retrieving data. Please check your internet'
          ' access or try again later. If the problem persists,',
  'sendReport': 'Send a report',
  'reportSubject': 'The application № 099 fails to install the translation',
  'reportBody': 'Enter a full description of your error',
  'reportCanSend': "Can't send report",
  'next': 'Next',
  'ignore': 'Ignore',
  'start': 'Start',
  'save': 'Save',
  'moduleCalendarHeader': 'Daily reading',
  'moduleCalendarContent':
      'The application offers daily verses from your community that '
          'you can read and share with your loved ones.',
  'moduleBibleHeader': 'Free access to several translations!',
  'moduleBibleContent':
      'In the "translations" menu, you have the possibility of '
          'downloading a translation or several translations according to '
          'your preferences. You also have the possibility of making a '
          'filter: it is fast and efficient \uD83D\uDE07',
  'moduleWelcomeContent':
      'This application has been designed to allow \n \t- Any believing'
          ' community to create and share publications with their followers'
          ' \n \t- Any family to improve awareness of speech \n \t- Any'
          ' person to better analyze and share the St scriptures',
  'moduleWelcomeHeader': 'Welcome!',
  'selectPreferredLang': 'Please select your preferred language',
  'french': 'French',
  'english': 'English',
  'oneTimothy': '1 Timothy',
  'psalms': 'Psalms',
  'genesis': 'Genesis',
  'exodus': 'Exodus',
  'leviticus': 'Leviticus',
  'numbers': 'Numbers',
  'deuteronomy': 'Deuteronomy',
  'joshua': 'Joshua',
  'judges': 'Judges',
  'ruth': 'Ruth',
  'oneSamuel': '1 Samuel',
  'twoSamuel': '2 Samuel',
  'oneKings': '1 Kings',
  'twoKings': '2 Kings',
  'oneChronicles': '1 Chronicles',
  'twoChronicles': '2 Chronicles',
  'ezra': 'Ezra',
  'nehemiah': 'Nehemiah',
  'esther': 'Esther',
  'job': 'Job',
  'proverbs': 'Proverbs',
  'ecclesiastes': 'Ecclesiastes',
  'songOfSongs': 'Song of Songs',
  'isaiah': 'Isaiah',
  'jeremiah': 'Jeremiah',
  'lamentations': 'Lamentations',
  'ezekiel': 'Ezekiel',
  'daniel': 'Daniel',
  'hosea': 'HHosea',
  'joel': 'Joel',
  'amos': 'Amos',
  'obadiah': 'Obadiah',
  'jonah': 'Jonah',
  'micah': 'Micah',
  'nahum': 'Nahum',
  'habakkuk': 'Habakkuk',
  'zephaniah': 'Zephaniah',
  'haggai': 'Haggai',
  'zechariah': 'Zechariah',
  'malachi': 'Malachi',
  'matthew': 'Matthew',
  'mark': 'Mark',
  'luke': 'Luke',
  'john': 'John',
  'acts': 'Acts',
  'romans': 'Romans',
  'oneCorinthians': '1 Corinthians',
  'twoCorinthians': '2 Corinthians',
  'galatians': 'Galatians',
  'ephesians': 'Ephesians',
  'philippians': 'Philippians',
  'colossians': 'Colossians',
  'oneThessalonians': '1 Thessalonians',
  'twoThessalonians': '2 Thessalonians',
  'twoTimothy': '2 Timothy',
  'titus': 'Titus',
  'philemon': 'Philemon',
  'hebrews': 'Hebrews',
  'james': 'Jame',
  'onePeter': '1 Peter',
  'twoPeter': '2 Peter',
  'oneJohn': '1 John',
  'twoJohn': '2 John',
  'treeJohn': '3 John',
  'jude': 'Jude',
  'revelation': 'Revelation',
  'youCanChoiceTranslateStart': 'You can download the',
  'youCanChoiceTranslateMiddle': 'or',
  'youCanChoiceTranslateEnd': 'version'
};
