part of '../app_intl.dart';

const Map<String, String> _sourceFr = <String, String>{
  'home': 'Accueil',
  'calendar': 'Calendrier',
  'favorites': 'Favoris',
  'translation': 'Traduction',
  'evaluate': "Evaluer l'application",
  'share': 'Partager {lapp}',
  'shareMsg': 'Hey! voici une application de partage évangélique'
      ' très intéressante \uD83D\uDC49 {url}',
  'appName': 'Calendrier biblique',
  'lapp': "l'application",
  'verse': 'Verset',
  'noTranslation': 'Aucune traduction',
  'downloadLeastOneTranslate':
      'Veuillez télécharger au moins une traduction pour '
          "accéder aux fonctionnalités de l'application",
  'ok': "D'accord",
  'confirmDelete': 'Confirmation de suppression',
  'reallyWantIt': 'Voulez-vous vraiment supprimer la traduction',
  'delete': 'Supprimer',
  'cancel': 'Annuler',
  'youHaveXTranslation': 'Vous possédez {count} traduction{addS}',
  'addTranslation': 'Ajouter une traduction',
  'def': 'Défaut',
  'markAsPrincipal': 'Définir comme traduction principal',
  'favoriteNotFound': 'Favoris non trouvés',
  'textOfD': 'Texte du Jour',
  'monday': 'Lundi',
  'tuesday': 'Mardi',
  'wednesday': 'Mercredi',
  'thursday': 'Jeudi',
  'friday': 'Vendredi',
  'saturday': 'Samedi',
  'sunday': 'Dimanche',
  'notFoundInCurrentTranslation':
      "introuvable dans la traduction actuelle. S'il vous plaît",
  'select': 'Sélectionner',
  'or': 'Ou',
  'download': 'Télécharger',
  'appropriateTranslation': 'La traduction appropriée',
  'language': 'Langue',
  'size': 'Taille',
  'downloaded': 'Téléchargé',
  'downloading': 'Téléchargement',
  'updating': 'Mise à jour en cours',
  'updatingDb': 'Mise à jour de la base de données en cours',
  'error': 'Erreur',
  'errorDownloadDataMsg':
      'Erreur lors de la récupération des données. Veuillez vérifier votre '
          'accès Internet ou réessayer plus tard. Si le problème persiste,',
  'sendReport': 'Envoyez un rapport',
  'reportSubject':
      "L'application № 099 ne parvient pas à installer la traduction",
  'reportBody': 'Entrez une description complète de votre erreur',
  'reportCanSend': "Impossible d'envoyer un rapport",
  'next': 'Suivant',
  'ignore': 'Ignorer',
  'start': 'Commencer',
  'save': 'Enregistrer',
  'moduleCalendarHeader': 'Lecture quotidienne',
  'moduleCalendarContent':
      "L'application propose des versets quotidiens de votre communauté que"
          ' vous pouvez lire et partager avec vos proches.',
  'moduleBibleHeader': 'Un accès libre et gratuit a plusieur traduction!',
  'moduleBibleContent':
      'Dans le menu «traductions», vous avez la possibilité de télécharger une'
          ' traduction ou plusieurs traductions selon vos préférences.'
          ' Vous avez également la possibilité de réaliser un filtre: '
          'il est rapide et efficace \uD83D\uDE07',
  'moduleWelcomeContent':
      'Cette application a été conçue pour permettre à \n \t- Toute communauté'
          ' croyante de créer et de partager des publications avec ses'
          ' abonnés \n \t- Toute famille pour améliorer la prise de '
          'conscience de la parole \n \t- Toute personne pour mieux '
          'analyser et partager les écritures St',
  'moduleWelcomeHeader': 'Bienvenue!',
  'selectPreferredLang': 'Veuillez sélectionner votre langue préférée',
  'french': 'Français',
  'english': 'Anglais',
  'oneTimothy': '1 Timothée',
  'psalms': 'Psaumes',
  'genesis': 'Genèse',
  'exodus': 'Exode',
  'leviticus': 'Lévitique',
  'numbers': 'Nombres',
  'deuteronomy': 'Deuteronome',
  'joshua': 'Josué',
  'judges': 'Juges',
  'ruth': 'Ruth',
  'oneSamuel': '1 Samuel',
  'twoSamuel': '2 Samuel',
  'oneKings': '1 Rois',
  'twoKings': '2 Rois',
  'oneChronicles': '1 Chroniques',
  'twoChronicles': '2 Chroniques',
  'ezra': 'Esdras',
  'nehemiah': 'Néthémie',
  'esther': 'Esther',
  'job': 'Job',
  'proverbs': 'Proverbes',
  'ecclesiastes': 'Ecclésiaste',
  'songOfSongs': 'Cantique des Cantiques',
  'isaiah': 'Esaïe',
  'jeremiah': 'Jérémie',
  'lamentations': 'Lamentations',
  'ezekiel': 'Ezéchiel',
  'daniel': 'Daniel',
  'hosea': 'Osée',
  'joel': 'Joël',
  'amos': 'Amos',
  'obadiah': 'Abdias',
  'jonah': 'Jonas',
  'micah': 'Michée',
  'nahum': 'Nahum',
  'habakkuk': 'Habacuc',
  'zephaniah': 'Sophonie',
  'haggai': 'Aggée',
  'zechariah': 'Zacharie',
  'malachi': 'Malachie',
  'matthew': 'Matthieu',
  'mark': 'Marc',
  'luke': 'Luc',
  'john': 'Jean',
  'acts': 'Actes',
  'romans': 'Romains',
  'oneCorinthians': '1 Corinthiens',
  'twoCorinthians': '2 Corinthiens',
  'galatians': 'Galates',
  'ephesians': 'Ephésiens',
  'philippians': 'Philippiens',
  'colossians': 'Colossiens',
  'oneThessalonians': '1 Thessaloniciens',
  'twoThessalonians': '2 Thessaloniciens',
  'twoTimothy': '2 Timothée',
  'titus': 'Tite',
  'philemon': 'Philémon',
  'hebrews': 'Hébreux',
  'james': 'Jacques',
  'onePeter': '1 Pierre',
  'twoPeter': '2 Pierre',
  'oneJohn': '1 Jean',
  'twoJohn': '2 Jean',
  'treeJohn': '3 Jean',
  'jude': 'Jude',
  'revelation': 'Apocalypse',
  'youCanChoiceTranslateStart': 'Vous pouvez télécharger la version',
  'youCanChoiceTranslateMiddle': 'ou',
  'youCanChoiceTranslateEnd': ''
};
