on: push
name: Code quality and Test
jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.4'
    - run: flutter pub get
    - run: flutter analyze
    - run: echo 'code coverage repport'
    - run: curl -Os https://uploader.codecov.io/latest/linux/codecov
    - run: chmod +x codecov
    - run: echo './codecov -t' ${CODECOV_TOKEN}
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.4'
    - run: flutter pub get
    - run: flutter test
