on: push
name: Code quality and Test
jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.3'
    - run: flutter pub get
    - run: flutter analyze
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.3'
    - run: flutter pub get
    - run: flutter test
